import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, DataSource } from 'typeorm';
import { Seat, SeatStatus, Screen, ScreenStatus } from '../../entities';
import {
  throwError,
  PaginatedResponse,
  encryptId,
  ICurrentUser,
} from '@moviebooking/common';
import { CreateSeatDto } from './dto/create-seat.dto';
import { UpdateSeatDto } from './dto/update-seat.dto';
import { ListSeatsQueryDto } from './dto/list-seats-query.dto';
import { BulkCreateSeatsDto } from './dto/bulk-create-seats.dto';

@Injectable()
export class SeatsService {
  private readonly logger = new Logger('SeatsService');

  constructor(
    @InjectRepository(Seat)
    private readonly seatRepository: Repository<Seat>,
    @InjectRepository(Screen)
    private readonly screenRepository: Repository<Screen>,
    private readonly dataSource: DataSource,
  ) {}

  async create(
    theatreId: number,
    screenId: number,
    dto: CreateSeatDto,
    user?: ICurrentUser,
  ) {
    await this.verifyScreenBelongsToTheatre(theatreId, screenId, user);
    await this.checkSeatUniqueness(screenId, dto.rowLabel, dto.seatNumber);

    // seatCode is auto-generated by entity @BeforeInsert hook
    const seat = this.seatRepository.create({
      ...dto,
      screenId,
      status: SeatStatus.ACTIVE,
    });

    const saved = await this.seatRepository.save(seat);
    return this.mapResponse(saved);
  }

  async bulkCreate(
    theatreId: number,
    screenId: number,
    dto: BulkCreateSeatsDto,
    user?: ICurrentUser,
  ) {
    this.logger.debug(
      `Bulk creating seats: theatre=${theatreId}, screen=${screenId}, range=${dto.startNumber}-${dto.endNumber}`,
    );

    await this.verifyScreenBelongsToTheatre(theatreId, screenId, user);
    this.validateBulkCreateInput(dto);

    const seatNumbers = this.generateSeatNumbers(dto.startNumber, dto.endNumber);

    // Prepare data - seatCode auto-generated by entity hook
    const seatData = seatNumbers.map(num => ({
      screenId,
      rowLabel: dto.rowLabel,
      seatNumber: num,
      seatType: dto.seatType,
      status: SeatStatus.ACTIVE,
    }));

    const queryRunner = this.dataSource.createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();

    try {
      const saved = await queryRunner.manager.save(
        Seat,
        seatData.map(data => queryRunner.manager.create(Seat, data)),
      );

      await queryRunner.commitTransaction();
      this.logger.log(`Successfully created ${saved.length} seats`);

      return {
        created: saved.length,
        seats: this.mapResponses(saved),
      };
    } catch (error) {
      await queryRunner.rollbackTransaction();

      if (this.isDuplicateConstraintError(error)) {
        this.logger.warn(`Duplicate seats attempted: screen=${screenId}, row=${dto.rowLabel}`);
        throwError('DUPLICATE_RESOURCE', `Seats already exist in row ${dto.rowLabel}. Please check your range.`);
      }

      this.logger.error(`Failed to bulk create seats: ${error.message}`, error.stack);
      throw error;
    } finally {
      await queryRunner.release();
    }
  }

  async findAll(
    theatreId: number,
    screenId: number,
    query: ListSeatsQueryDto,
    user?: ICurrentUser,
  ) {
    const { page = 1, pageSize = 100, rowLabel } = query;

    await this.verifyScreenBelongsToTheatre(theatreId, screenId, user);

    const qb = this.seatRepository
      .createQueryBuilder('seat')
      .where('seat.screenId = :screenId', { screenId });

    // Guest: ACTIVE only
    if (!user) {
      qb.andWhere('seat.status = :status', { status: SeatStatus.ACTIVE });
    }

    if (rowLabel) {
      qb.andWhere('seat.rowLabel = :rowLabel', { rowLabel });
    }

    qb.orderBy('seat.rowLabel', 'ASC')
      .addOrderBy('seat.seatNumber', 'ASC')
      .skip((page - 1) * pageSize)
      .take(pageSize);

    const [seats, total] = await qb.getManyAndCount();

    return new PaginatedResponse(this.mapResponses(seats), total, page, pageSize);
  }

  async findOne(
    theatreId: number,
    screenId: number,
    seatId: number,
    user?: ICurrentUser,
  ) {
    await this.verifyScreenBelongsToTheatre(theatreId, screenId, user);

    const whereCondition: any = { id: seatId, screenId };

    if (!user) {
      whereCondition.status = SeatStatus.ACTIVE;
    }

    const seat = await this.seatRepository.findOne({ where: whereCondition });

    if (!seat) {
      throwError('NOT_FOUND', 'Seat not found');
    }

    return this.mapResponse(seat);
  }

  async update(
    theatreId: number,
    screenId: number,
    seatId: number,
    dto: UpdateSeatDto,
  ) {
    await this.verifyScreenBelongsToTheatre(theatreId, screenId);

    const seat = await this.seatRepository.findOne({
      where: { id: seatId, screenId },
    });

    if (!seat) {
      throwError('NOT_FOUND', 'Seat not found');
    }

    // If changing rowLabel or seatNumber, check uniqueness
    if (dto.rowLabel !== undefined || dto.seatNumber !== undefined) {
      const newRowLabel = dto.rowLabel ?? seat.rowLabel;
      const newSeatNumber = dto.seatNumber ?? seat.seatNumber;

      if (newRowLabel !== seat.rowLabel || newSeatNumber !== seat.seatNumber) {
        await this.checkSeatUniqueness(screenId, newRowLabel, newSeatNumber, seatId);
      }
    }

    Object.assign(seat, dto);
    const updated = await this.seatRepository.save(seat);
    return this.mapResponse(updated);
  }

  async remove(theatreId: number, screenId: number, seatId: number) {
    await this.verifyScreenBelongsToTheatre(theatreId, screenId);

    const seat = await this.seatRepository.findOne({
      where: { id: seatId, screenId },
    });

    if (!seat) {
      throwError('NOT_FOUND', 'Seat not found');
    }

    seat.status = SeatStatus.INACTIVE;
    await this.seatRepository.save(seat);

    return this.mapResponse(seat);
  }

  // ============ Private Helper Methods ============

  private async verifyScreenBelongsToTheatre(
    theatreId: number,
    screenId: number,
    user?: ICurrentUser,
  ): Promise<Screen> {
    const whereCondition: any = { id: screenId, theatreId };

    if (!user) {
      whereCondition.status = ScreenStatus.ACTIVE;
    }

    const screen = await this.screenRepository.findOne({ where: whereCondition });

    if (!screen) {
      throwError('NOT_FOUND', 'Screen not found or does not belong to this theatre');
    }

    return screen;
  }

  private async checkSeatUniqueness(
    screenId: number,
    rowLabel: string,
    seatNumber: number,
    excludeId?: number,
  ): Promise<void> {
    const qb = this.seatRepository
      .createQueryBuilder('seat')
      .where('seat.screenId = :screenId', { screenId })
      .andWhere('seat.rowLabel = :rowLabel', { rowLabel })
      .andWhere('seat.seatNumber = :seatNumber', { seatNumber });

    if (excludeId) {
      qb.andWhere('seat.id != :excludeId', { excludeId });
    }

    const existing = await qb.getOne();

    if (existing) {
      throwError('DUPLICATE_RESOURCE', `Seat ${rowLabel}${seatNumber} already exists in this screen`);
    }
  }

  private validateBulkCreateInput(dto: BulkCreateSeatsDto): void {
    if (dto.startNumber > dto.endNumber) {
      throwError('VALIDATION_ERROR', 'startNumber must be less than or equal to endNumber');
    }

    const count = dto.endNumber - dto.startNumber + 1;
    if (count > 100) {
      throwError('VALIDATION_ERROR', 'Cannot create more than 100 seats at once');
    }

    if (dto.startNumber < 1) {
      throwError('VALIDATION_ERROR', 'seatNumber must be greater than 0');
    }
  }

  private generateSeatNumbers(start: number, end: number): number[] {
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }

  private isDuplicateConstraintError(error: any): boolean {
    return (
      error.code === 'ER_DUP_ENTRY' ||
      error.code === '23505' ||
      (error.constraint && error.constraint.includes('unique')) ||
      (error.message && error.message.includes('UNIQUE constraint'))
    );
  }

  private mapResponse(seat: Seat) {
    return {
      id: encryptId(seat.id),
      screenId: encryptId(seat.screenId),
      seatCode: seat.seatCode,
      rowLabel: seat.rowLabel,
      seatNumber: seat.seatNumber,
      seatType: seat.seatType,
      status: seat.status,
      createdAt: seat.createdAt,
      updatedAt: seat.updatedAt,
    };
  }

  private mapResponses(seats: Seat[]) {
    return seats.map(seat => this.mapResponse(seat));
  }
}
